### PR TITLE
added compatibility with comfy ui

### PR DESCRIPTION
**Pull request by alexgenovese**

### CODE REVIEW

**Comment by liusida** [comment]
Thanks for your PR, @alexgenovese . 

I guess you did this for devices other than nvidia GPUs, right?
The problem of this modification is that `Pytorch_Retinaface` will be dependent on `comfy`. I was trying to avoid the reference of comfy in `Pytorch_Retinaface` to make it agnostic.

Let me see if there's another way to achieve this.

My suggestion is to change this line:
https://github.com/liusida/ComfyUI-AutoCropFaces/blob/30c0007ee6aea7637aa2bf730958f0c57699aedb/__init__.py#L63C1-L64C1
, adding a `device=get_torch_device()` as an additional parameter.

Do you like to implement that instead and test the change with your device?

**Comment by bigcat88** [comment]
May I ask when this or alternative proposal be merged?

Thank you.

**Comment by liusida** [comment]
oops! I've totally forgotten this PR...

Never mind, I've modified the code already. And sorry @alexgenovese , I'll close this PR for now.

**Comment by liusida** [comment]
the modification has been done this way:

https://github.com/liusida/ComfyUI-AutoCropFaces/commit/e92d5f4cc4f43a4b8935e263a197b17a4417f059

**Comment by bigcat88** [comment]
> the modification has been done this way:

@liusida May I ask why this method was chosen?

If I see it correctly, after that commit this Node itself determines which device to use, and even if another device was chosen for execution in ComfUIi, Node will ignore it?

will be such solution in just 2 lines(instead of that commit) more simpler or does it has it own downsides?

https://github.com/liusida/ComfyUI-AutoCropFaces/compare/main...Visionatrix:ComfyUI-AutoCropFaces:main

**Comment by liusida** [comment]
You are right. I should use ComfyUI's settings. I think I forgot that this is a ComfyUI node and tried to make it less dependent on ComfyUI.

Let me revise it latter.

**Pull request closed without merging**
